<h1 class="page-header">
    Browsing <?php echo ucfirst($entityType) ?>
    <?php if ($this->isGranted($this->basePermission . '.add')): ?>
    <a class="btn btn-primary pull-right" role="button" title="Add New"
       href="<?php echo $this->url($this->indexRoute . '/add') ?>">
        <span class="glyphicon glyphicon-plus"></span>
    </a>
    <?php endif ?>
</h1>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Last Modified</th>
            <th>Created</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if ($this->isGranted($this->basePermission . '.browse')): 
            foreach ($list as $entity):
            ?>
            <tr<?php echo $entity->isDisabled() ? ' class="danger"' : null ?>>
                <td><?php echo $this->escapeHtml($entity->getId()) ?></td>
                <td><?php echo $this->escapeHtml($entity->getName()) ?></td>
                <td><?php echo $this->escapeHtml($entity->getDescription()) ?></td>
                <td><?php echo $this->time($entity->getLastModified()) ?></td>
                <td><?php echo $this->time($entity->getCreated()) ?></td>
                <td>
                    <?php if ($entity->isDisabled()): ?>
                        <?php if ($this->isGranted($this->basePermission . '.enable')): ?>
                    <a class="btn btn-success" role="button" title="Enable"
                       href="<?php echo $this->url($this->indexRoute . '/enable', ['id' => $entity->getId()]) ?>">
                        <span class="glyphicon glyphicon-off"></span>
                    </a>
                        <?php endif ?>
                    <?php else: ?>
                    <div class="btn-group" role="group" aria-label="Actions">
                        <?php if ($this->isGranted($this->basePermission . '.disable')): ?>
                        <a class="btn btn-warning" role="button" title="Disable"
                           href="<?php echo $this->url($this->indexRoute . '/disable', ['id' => $entity->getId()]) ?>">
                            <span class="glyphicon glyphicon-off"></span>
                        </a>
                        <?php endif ?>
                        <?php if ($this->isGranted($this->basePermission . '.read')): ?>
                            <a class="btn btn-primary" role="button" title="View"
                               href="<?php echo $this->url($this->indexRoute . '/read', array('id' => $entity->getId())) ?>">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </a>
                        <?php endif ?>
                        <?php if ($this->isGranted($this->basePermission . '.edit')): ?>
                            <a class="btn btn-info" role="button" title="Edit"
                               href="<?php echo $this->url($this->indexRoute . '/edit', array('id' => $entity->getId())) ?>">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        <?php endif ?>
                        <?php if ($this->isGranted($this->basePermission . '.delete')): ?>
                        <a class="btn btn-danger" role="button" title="Delete"
                           href="<?php echo $this->url($this->indexRoute . '/delete', ['id' => $entity->getId()]) ?>">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <?php endif ?>
                    </div>
                    <?php endif ?>
                </td>
            </tr>
            <?php
            endforeach;
        endif;
        ?>
    </tbody>
</table>