<h1 class="page-header">
    Reading <?php echo $entityTitle ?>: <em><?php echo $entity ?></em>
</h1>
<form class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <p class="form-control-static">
                <?php echo $this->escapeHtml($entity->getName()) ?>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Description</label>
        <div class="col-sm-10">
            <p class="form-control-static">
                <?php echo $this->escapeHtml($entity->getDescription()) ?>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Last Modified</label>
        <div class="col-sm-10">
            <p class="form-control-static">
                <?php echo $this->time($entity->getLastModified()) ?>
            </p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Created</label>
        <div class="col-sm-10">
            <p class="form-control-static">
                <?php echo $this->time($entity->getCreated()) ?>
            </p>
        </div>
    </div>
</form>