<?php
$camelFilter   = new Zend\Filter\Word\CamelCaseToSeparator;
$actionTitle   = strtolower($camelFilter->filter($dialogueType));
$entityTitle   = strtolower($camelFilter->filter($entityType));
$dialogueTitle = ucwords($actionTitle . ' ' . $entityTitle);
?>
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"
     aria-labelledby="admin-modal-label">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="admin-modal-label">
                    <?php echo $dialogueTitle ?>
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    <strong>Are you sure</strong> you really want to
                    <?php echo $actionTitle ?> the <?php echo $entityTitle ?>:
                    <em><?php echo $entity ?></em>?
                </p>
            </div>
            <div class="modal-footer">
                <?php
                $cancel = $form->get('buttons')->get('cancel');
                $cancel->setAttribute('data-href', $this->url($indexRoute));
                $cancel->setAttribute('data-dismiss', 'modal');
                echo $this->form($form);
                ?>
            </div>
        </div>
    </div>
</div>