<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"
     aria-labelledby="admin-modal-label">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="admin-modal-label">
                    <?php echo $dialogTitle ?>
                </h4>
            </div>
            <div class="modal-body">
                <?php echo $dialogBody ?>
            </div>
            <div class="modal-footer">
                <?php echo $this->form($form) ?>
            </div>
        </div>
    </div>
</div>